# Aggregate GEFS to Daily Level

Aggregate the GEFS data over the ensemble models, and produce data at the daily level, the same cadence as the Mesonet data.

In [1]:
import pandas as pd

Process the train data into daily format

In [2]:
gefs_training_df = pd.read_csv("../data/gefs/gefs_train.csv")
gefs_training_df.head()

,Upward_Long-Wave_Rad_Flux_surface,Upward_Short-Wave_Rad_Flux,Specific_humidity_height_above_ground,Downward_Long-Wave_Rad_Flux,Total_Column-Integrated_Condensate,Downward_Short-Wave_Rad_Flux,Precipitable_water,Total_precipitation,Total_cloud_cover,Temperature_surface,...,Maximum_temperature,Upward_Long-Wave_Rad_Flux,ens,fhour,lat,lon,time,intTime,intValidTime,Pressure
0,333.76056,0.0,0.004020,247.01898,0.0002,0.0,5.700000,0.0,0.0,275.60760,...,280.90344,255.59988,0,0 days 12:00:00.000000000,31.0,254.0,1994-01-01,1994010100,1994010112,102244.94
1,336.21130,0.0,0.003630,257.01898,0.0000,0.0,6.798102,0.0,0.0,276.50568,...,281.62622,252.67752,0,0 days 12:00:00.000000000,31.0,254.0,1994-01-02,1994010200,1994010212,101962.01
2,318.73020,0.0,0.001580,231.84859,0.0007,0.0,4.891023,0.0,0.0,272.48004,...,278.13170,242.08640,0,0 days 12:00:00.000000000,31.0,254.0,1994-01-03,1994010300,1994010312,102341.00
3,332.61664,0.0,0.001930,241.16321,0.0004,0.0,4.944364,0.0,0.0,274.79395,...,282.01617,254.67052,0,0 days 12:00:00.000000000,31.0,254.0,1994-01-04,1994010400,1994010412,102438.59
4,329.19788,0.0,0.002092,242.19736,0.0002,0.0,4.567267,0.0,0.0,274.73816,...,280.72284,254.01093,0,0 days 12:00:00.000000000,31.0,254.0,1994-01-05,1994010500,1994010512,101882.70

In [11]:
gefs_training_gb_time_df = (
    gefs_training_df
    .drop(["intTime","intValidTime"], axis=1)
    .groupby(["lat","lon","time"])
    .agg({"mean","min","max","std"})
    .reset_index()
)
gefs_training_gb_time_df.columns = [' '.join(col).strip() for col in gefs_training_gb_time_df.columns.values]
gefs_training_gb_time_df.head()

,lat,lon,time,Upward_Long-Wave_Rad_Flux_surface mean,Upward_Long-Wave_Rad_Flux_surface min,Upward_Long-Wave_Rad_Flux_surface std,Upward_Long-Wave_Rad_Flux_surface max,Upward_Short-Wave_Rad_Flux mean,Upward_Short-Wave_Rad_Flux min,Upward_Short-Wave_Rad_Flux std,...,Upward_Long-Wave_Rad_Flux std,Upward_Long-Wave_Rad_Flux max,ens mean,ens min,ens std,ens max,Pressure mean,Pressure min,Pressure std,Pressure max
0,31.0,254.0,1994-01-01,367.065219,324.00000,40.295247,422.75583,68.781818,0.0,63.209438,...,11.482474,281.09550,5,0,3.191424,10,102217.904727,101916.42,184.451255,102476.81
1,31.0,254.0,1994-01-02,368.057103,329.00000,36.823085,419.00000,69.690909,0.0,64.501184,...,9.825419,278.86664,5,0,3.191424,10,102173.175091,101924.96,153.622300,102467.37
2,31.0,254.0,1994-01-03,358.022946,309.02200,44.284551,418.46637,70.036364,0.0,64.539383,...,17.336351,279.30950,5,0,3.191424,10,102152.114182,101812.38,241.888780,102459.32
3,31.0,254.0,1994-01-04,366.386096,318.54144,42.917750,426.78842,69.727273,0.0,64.255985,...,13.590242,282.80730,5,0,3.191424,10,102382.628545,102041.37,166.193135,102632.57
4,31.0,254.0,1994-01-05,372.722521,321.57993,48.962837,436.33432,70.581818,0.0,65.015010,...,14.535518,289.41656,5,0,3.191424,10,101443.177091,100905.18,379.803869,101964.53

In [10]:
gefs_training_gb_time_df.shape

(736272, 67)

In [ ]:
gefs_training_gb_time_df.to_csv("../data/gefs/gefs_train_daily.csv", index=False)

Process the test data into daily format

In [13]:
gefs_test_df = pd.read_csv("../data/gefs/gefs_test.csv")
gefs_test_df.head()

,Upward_Long-Wave_Rad_Flux_surface,Upward_Short-Wave_Rad_Flux,Temperature_surface,Total_cloud_cover,Pressure,Total_precipitation,Specific_humidity_height_above_ground,Downward_Short-Wave_Rad_Flux,Precipitable_water,Downward_Long-Wave_Rad_Flux,...,Total_Column-Integrated_Condensate,Minimum_temperature,ens,fhour,lat,lon,time,intTime,intValidTime,Upward_Long-Wave_Rad_Flux
0,323.05624,0.0,272.82745,0.00,103451.44,0.0,0.002370,0.0,4.600000,230.33810,...,0.0002,274.58176,0,0 days 12:00:00.000000000,31.0,254.0,2008-01-01,2008010100,2008010112,247.41327
1,311.35620,0.0,270.86688,0.18,104056.45,0.0,0.001270,0.0,6.084514,237.00000,...,0.1780,271.78336,0,0 days 12:00:00.000000000,31.0,254.0,2008-01-02,2008010200,2008010212,182.33313
2,309.69135,0.0,270.95956,0.00,103235.97,0.0,0.001740,0.0,7.700000,230.17114,...,0.0060,272.65146,0,0 days 12:00:00.000000000,31.0,254.0,2008-01-03,2008010300,2008010312,235.13397
3,330.50827,0.0,275.10320,0.11,102106.59,0.0,0.002562,0.0,11.600000,282.66190,...,0.1075,277.63263,0,0 days 12:00:00.000000000,31.0,254.0,2008-01-04,2008010400,2008010412,170.60030
4,329.01746,0.0,274.84494,0.00,101985.16,0.0,0.005176,0.0,10.741630,265.00000,...,0.0001,278.26822,0,0 days 12:00:00.000000000,31.0,254.0,2008-01-05,2008010500,2008010512,251.53897

In [14]:
gefs_test_gb_time_df = (
    gefs_test_df
    .drop(["intTime","intValidTime"], axis=1)
    .groupby(["lat","lon","time"])
    .agg({"mean","min","max","std"})
    .reset_index()
)
gefs_test_gb_time_df.columns = [' '.join(col).strip() for col in gefs_test_gb_time_df.columns.values]
gefs_test_gb_time_df.head()

,lat,lon,time,Upward_Long-Wave_Rad_Flux_surface mean,Upward_Long-Wave_Rad_Flux_surface min,Upward_Long-Wave_Rad_Flux_surface std,Upward_Long-Wave_Rad_Flux_surface max,Upward_Short-Wave_Rad_Flux mean,Upward_Short-Wave_Rad_Flux min,Upward_Short-Wave_Rad_Flux std,...,Minimum_temperature std,Minimum_temperature max,ens mean,ens min,ens std,ens max,Upward_Long-Wave_Rad_Flux mean,Upward_Long-Wave_Rad_Flux min,Upward_Long-Wave_Rad_Flux std,Upward_Long-Wave_Rad_Flux max
0,31.0,254.0,2008-01-01,345.748174,309.91100,31.041528,388.96954,69.072727,0.0,63.526272,...,2.283003,278.31046,5,0,3.191424,10,248.366614,203.07524,13.678166,268.67730
1,31.0,254.0,2008-01-02,337.567863,305.98132,28.457281,380.89502,53.000000,0.0,54.203663,...,2.472995,277.46613,5,0,3.191424,10,175.444051,120.95181,36.193206,250.08917
2,31.0,254.0,2008-01-03,347.884433,304.54070,41.582406,403.97116,64.618182,0.0,60.601763,...,3.472172,280.01797,5,0,3.191424,10,231.017664,203.27194,11.723808,256.63130
3,31.0,254.0,2008-01-04,358.325496,315.25410,32.371736,421.76917,33.854545,0.0,32.107700,...,3.161447,285.38168,5,0,3.191424,10,167.022968,138.02797,17.233456,217.55034
4,31.0,254.0,2008-01-05,372.115805,322.02250,47.615339,436.35626,66.054545,0.0,61.236160,...,3.855979,286.44890,5,0,3.191424,10,253.732123,228.18376,11.909200,276.60052

In [16]:
gefs_test_gb_time_df.shape

(258624, 67)

In [15]:
gefs_test_gb_time_df.to_csv("../data/gefs/gefs_test_daily.csv", index=False)